SELECT DISTINCT a.USER_ID, a.PRODUCT_ID
FROM ONLINE_SALE a
JOIN ONLINE_SALE b ON a.USER_ID = b.USER_ID AND a.PRODUCT_ID = b.PRODUCT_ID
WHERE a.SALES_DATE < b.SALES_DATE
ORDER BY a.USER_ID ASC, a.PRODUCT_ID DESC;